version: '3.5'

services:
  rabbit:
    image: 'rabbitmq:management'
    environment:
      RABBITMQ_ERLANG_COOKIE: 'SWQOKODSQALRPCLNMEQG'
      RABBITMQ_DEFAULT_USER: 'rabbitmq'
      RABBITMQ_DEFAULT_PASS: 'rabbitmq'
      RABBITMQ_DEFAULT_VHOST: '/'
    tty: true

networks:
  default:
    name: golevelup-nestjs-network
